"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Node = { id:string; name:string; role:"ingress"|"egress"|"both"; public_address:string; private_address:string; public_interface:string; private_interface:string; status:string; last_seen_at:string };
type Rule = { id:string; mode:"dual_managed"|"exit_only"; name:string; protocol:"tcp"|"udp"|"both"; ingress_node_id:string; egress_node_id:string; listen_address:string; listen_port:number; relay_port:number; target_host:string; target_port:number; engine:"nftables"|"realm"; upload_mbps:number; download_mbps:number; burst_kbytes:number; enabled:boolean };
type Point = { bucket:string; upload_bytes:number; download_bytes:number };
type Summary = { online_nodes:number; total_nodes:number; enabled_rules:number; total_rules:number; today_upload:number; today_download:number; recent_traffic:Point[] };
type View = "overview"|"nodes"|"rules"|"traffic";

const demoNodes:Node[] = [
  {id:"in-gz",name:"广州入口",role:"ingress",public_address:"203.0.113.18",private_address:"10.24.0.2",public_interface:"eth0",private_interface:"wg0",status:"online",last_seen_at:new Date().toISOString()},
  {id:"out-hkg",name:"香港出口",role:"egress",public_address:"198.51.100.24",private_address:"10.24.0.3",public_interface:"eth0",private_interface:"wg0",status:"online",last_seen_at:new Date().toISOString()},
  {id:"out-sg",name:"新加坡备用",role:"egress",public_address:"198.51.100.52",private_address:"10.24.0.4",public_interface:"ens3",private_interface:"wg0",status:"offline",last_seen_at:new Date(Date.now()-3600_000).toISOString()},
];
const demoRules:Rule[] = [
  {id:"r1",mode:"dual_managed",name:"广州 → 香港 → 游戏",protocol:"both",ingress_node_id:"in-gz",egress_node_id:"out-hkg",listen_address:"0.0.0.0",listen_port:24444,relay_port:32444,target_host:"192.0.2.88",target_port:24444,engine:"nftables",upload_mbps:30,download_mbps:100,burst_kbytes:512,enabled:true},
  {id:"r2",mode:"exit_only",name:"已有专线 → 远程桌面",protocol:"both",ingress_node_id:"out-hkg",egress_node_id:"out-hkg",listen_address:"10.24.0.3",listen_port:33890,relay_port:33890,target_host:"192.0.2.91",target_port:3389,engine:"realm",upload_mbps:10,download_mbps:40,burst_kbytes:256,enabled:true},
];
const demoPoints = Array.from({length:24},(_,i)=>({bucket:new Date(Date.now()-(23-i)*3600_000).toISOString(),upload_bytes:(8+Math.sin(i/2)*4)*1024**3/24,download_bytes:(38+Math.cos(i/3)*12)*1024**3/24}));
const demoSummary:Summary={online_nodes:2,total_nodes:3,enabled_rules:2,total_rules:2,today_upload:8.4*1024**3,today_download:38.6*1024**3,recent_traffic:demoPoints};

const emptyRule:Omit<Rule,"id">={mode:"dual_managed",name:"",protocol:"both",ingress_node_id:"",egress_node_id:"",listen_address:"",listen_port:10000,relay_port:0,target_host:"",target_port:0,engine:"nftables",upload_mbps:0,download_mbps:0,burst_kbytes:512,enabled:true};
const emptyNode={name:"",role:"ingress" as const,public_address:"",private_address:"",public_interface:"eth0",private_interface:"wg0"};

async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});if(!response.ok){let message=`请求失败 (${response.status})`;try{message=(await response.json()).error||message}catch{/* 响应可能不是 JSON */}throw new Error(message)}if(response.status===204)return undefined as T;return response.json()}
function bytes(value:number){if(!Number.isFinite(value))return "0 B";const units=["B","KB","MB","GB","TB"];let n=value,i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n.toFixed(i>2?2:1)} ${units[i]}`}
function roleName(role:Node["role"]){return role==="ingress"?"入口":role==="egress"?"出口":"入口 / 出口"}
function nodeName(nodes:Node[],id:string){return nodes.find(n=>n.id===id)?.name||id}

export default function Home(){
  const [view,setView]=useState<View>("overview"),[authenticated,setAuthenticated]=useState<boolean|null>(null),[demo,setDemo]=useState(false),[nodes,setNodes]=useState<Node[]>([]),[rules,setRules]=useState<Rule[]>([]),[summary,setSummary]=useState<Summary>(demoSummary),[traffic,setTraffic]=useState<Point[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[ruleModal,setRuleModal]=useState(false),[nodeModal,setNodeModal]=useState(false),[credential,setCredential]=useState<{nodeId:string;token:string}|null>(null);
  const load=useCallback(async()=>{try{const [n,r,s,t]=await Promise.all([api<Node[]>("/api/v1/nodes"),api<Rule[]>("/api/v1/rules"),api<Summary>("/api/v1/dashboard"),api<Point[]>("/api/v1/traffic?hours=24")]);setNodes(n);setRules(r);setSummary(s);setTraffic(t);setAuthenticated(true);setDemo(false)}catch{setAuthenticated(false)}},[]);
  // The initial request synchronizes React with the external controller.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const activateDemo=()=>{setNodes(demoNodes);setRules(demoRules);setSummary(demoSummary);setTraffic(demoPoints);setAuthenticated(true);setDemo(true)};
  if(authenticated===null)return <div className="boot"><span className="pulse"/>正在连接控制端</div>;
  if(!authenticated)return <Login onSuccess={load} onDemo={activateDemo}/>;
  const refresh=demo?async()=>{}:load;
  return <div className="shell">
    <Sidebar view={view} setView={setView} demo={demo}/>
    <main className="main">
      <header className="topbar"><div><p className="eyebrow">个人转发控制台</p><h1>{({overview:"网络总览",nodes:"服务器",rules:"转发规则",traffic:"流量统计"} as const)[view]}</h1></div><div className="top-actions"><span className="health"><i/>控制端正常</span><button className="primary" onClick={()=>view==="nodes"?setNodeModal(true):setRuleModal(true)}>＋ {view==="nodes"?"添加服务器":"新建转发"}</button></div></header>
      {demo&&<div className="notice">当前为界面预览数据。启动 Go 控制端后，这里会自动显示真实节点、规则和流量。</div>}
      {error&&<div className="error">{error}<button onClick={()=>setError("")}>×</button></div>}
      {view==="overview"&&<Overview summary={summary} nodes={nodes} rules={rules} points={traffic.length?traffic:summary.recent_traffic} onOpenRules={()=>setView("rules")}/>} 
      {view==="nodes"&&<Nodes nodes={nodes} onAdd={()=>setNodeModal(true)} onDelete={async(id)=>{if(!demo&&confirm("确认删除该节点？")){await api(`/api/v1/nodes/${id}`,{method:"DELETE"});await refresh()}}}/>} 
      {view==="rules"&&<Rules nodes={nodes} rules={rules} onAdd={()=>setRuleModal(true)} onToggle={async(rule)=>{if(demo){setRules(current=>current.map(r=>r.id===rule.id?{...r,enabled:!r.enabled}:r));return}await api(`/api/v1/rules/${rule.id}`,{method:"PUT",body:JSON.stringify({...rule,enabled:!rule.enabled})});await refresh()}} onDelete={async(id)=>{if(demo){setRules(current=>current.filter(r=>r.id!==id));return}if(confirm("确认删除该规则及其统计关联？")){await api(`/api/v1/rules/${id}`,{method:"DELETE"});await refresh()}}}/>} 
      {view==="traffic"&&<Traffic rules={rules} points={traffic.length?traffic:summary.recent_traffic} summary={summary}/>} 
    </main>
    {ruleModal&&<RuleModal nodes={nodes} busy={busy} onClose={()=>setRuleModal(false)} onSave={async(rule)=>{setBusy(true);try{if(demo){const ingress=nodes.find(n=>n.id===rule.ingress_node_id),egress=nodes.find(n=>n.id===rule.egress_node_id);setRules(current=>[{...rule,id:`demo-${Date.now()}`,name:rule.mode==="dual_managed"?`${ingress?.name} → ${egress?.name} → ${rule.target_host}`:`已有专线 → ${egress?.name} → ${rule.target_host}`,ingress_node_id:rule.mode==="exit_only"?rule.egress_node_id:rule.ingress_node_id,listen_address:rule.mode==="exit_only"?(rule.listen_address||egress?.private_address||""):"0.0.0.0",relay_port:rule.mode==="exit_only"?rule.listen_port:30000+rule.listen_port%30000} as Rule,...current])}else{await api("/api/v1/rules",{method:"POST",body:JSON.stringify(rule)});await refresh()}setRuleModal(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>} 
    {nodeModal&&<NodeModal busy={busy} credential={credential} onClose={()=>{setNodeModal(false);setCredential(null)}} onSave={async(node)=>{setBusy(true);try{if(demo){setNodes(current=>[...current,{...node,id:`demo-${Date.now()}`,status:"offline",last_seen_at:""}])}else{const result=await api<{node:Node;agent_token:string}>("/api/v1/nodes",{method:"POST",body:JSON.stringify(node)});setCredential({nodeId:result.node.id,token:result.agent_token});await refresh();return}setNodeModal(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>} 
  </div>
}

function Login({onSuccess,onDemo}:{onSuccess:()=>Promise<void>;onDemo:()=>void}){const [password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/v1/login",{method:"POST",body:JSON.stringify({password})});await onSuccess()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}return <div className="login-page"><div className="login-brand"><Logo/><div><b>Relay Panel</b><span>专线端口转发</span></div></div><div className="login-card"><div className="login-mark"><span>RP</span></div><p className="eyebrow">安全管理入口</p><h1>欢迎回来</h1><p>登录以管理您的入口、出口与落地转发。</p><form onSubmit={submit}><label>管理员密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入控制端密码"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?"正在登录…":"进入控制台"}</button></form><button className="text-button" onClick={onDemo}>预览管理界面 →</button></div><p className="login-foot">单管理员模式 · 本地数据 · Agent 加密鉴权</p></div>}

function Logo(){return <div className="logo"><span/><span/><span/></div>}
function Sidebar({view,setView,demo}:{view:View;setView:(v:View)=>void;demo:boolean}){const items:[View,string,string][]=[["overview","总览","⌁"],["nodes","服务器","◇"],["rules","转发规则","⇄"],["traffic","流量统计","▥"]];return <aside className="sidebar"><div className="brand"><Logo/><div><b>Relay Panel</b><span>Personal Edition</span></div></div><nav>{items.map(([key,label,icon])=><button key={key} className={view===key?"active":""} onClick={()=>setView(key)}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-foot"><div className="mini-status"><i/><div><b>{demo?"预览模式":"系统运行中"}</b><span>{demo?"Demo data":"nftables ready"}</span></div></div><div className="version">v0.1.0 · 私人部署</div></div></aside>}

function Overview({summary,nodes,rules,points,onOpenRules}:{summary:Summary;nodes:Node[];rules:Rule[];points:Point[];onOpenRules:()=>void}){return <div className="page-grid"><section className="hero-panel"><div><p className="eyebrow">实时运行状态</p><h2>{summary.online_nodes}/{summary.total_nodes} 个节点在线</h2><p>入口经内网链路到出口，再安全转发到您的落地服务器。</p></div><div className="topology"><NodeDot label="本机"/><Line/><NodeDot label="入口" active/><Line privateLine/><NodeDot label="出口" active/><Line/><NodeDot label="落地"/></div></section><section className="stats-row"><Metric label="今日总流量" value={bytes(summary.today_upload+summary.today_download)} note={`↑ ${bytes(summary.today_upload)} · ↓ ${bytes(summary.today_download)}`} tone="violet"/><Metric label="启用规则" value={String(summary.enabled_rules)} note={`共 ${summary.total_rules} 条转发`} tone="cyan"/><Metric label="在线节点" value={String(summary.online_nodes)} note={`${summary.total_nodes-summary.online_nodes} 个离线`} tone="green"/><Metric label="限速策略" value={String(rules.filter(r=>r.upload_mbps||r.download_mbps).length)} note="独立上下行控制" tone="amber"/></section><section className="chart-card"><div className="section-head"><div><p className="eyebrow">最近 24 小时</p><h3>流量趋势</h3></div><div className="legend"><span className="down">下载</span><span className="up">上传</span></div></div><TrafficChart points={points}/></section><section className="side-card"><div className="section-head"><div><p className="eyebrow">节点状态</p><h3>转发链路</h3></div></div><div className="node-list">{nodes.slice(0,4).map(n=><div className="node-row" key={n.id}><span className={`node-icon ${n.status}`}>{n.role==="ingress"?"IN":"OUT"}</span><div><b>{n.name}</b><small>{n.private_address}</small></div><em className={n.status}>{n.status==="online"?"在线":"离线"}</em></div>)}</div><button className="outline wide" onClick={onOpenRules}>查看全部转发规则</button></section><section className="rules-card"><div className="section-head"><div><p className="eyebrow">最近配置</p><h3>活跃转发</h3></div></div><div className="compact-rules">{rules.slice(0,3).map(r=><div key={r.id}><span className={`protocol ${r.protocol}`}>{r.protocol.toUpperCase()}</span><b>{r.name}</b><small>:{r.listen_port} → {r.target_host}:{r.target_port}</small><em>{r.download_mbps?`${r.download_mbps} Mbps`:`不限速`}</em></div>)}</div></section></div>}
function NodeDot({label,active}:{label:string;active?:boolean}){return <div className={`topo-node ${active?"active":""}`}><span>{active?"●":"○"}</span><b>{label}</b></div>};function Line({privateLine}:{privateLine?:boolean}){return <div className={`topo-line ${privateLine?"private":""}`}><span>{privateLine?"内网":""}</span></div>}
function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

function TrafficChart({points}:{points:Point[]}){const values=points.slice(-24),max=Math.max(1,...values.map(p=>p.upload_bytes+p.download_bytes));return <div className="bars">{values.map((p,i)=><div className="bar-col" key={p.bucket||i} title={`${new Date(p.bucket).getHours()}:00 · ${bytes(p.upload_bytes+p.download_bytes)}`}><span className="bar-download" style={{height:`${Math.max(3,p.download_bytes/max*100)}%`}}/><span className="bar-upload" style={{height:`${Math.max(2,p.upload_bytes/max*100)}%`}}/><i>{i%4===0?`${new Date(p.bucket).getHours()}:00`:""}</i></div>)}</div>}

function Nodes({nodes,onAdd,onDelete}:{nodes:Node[];onAdd:()=>void;onDelete:(id:string)=>void}){return <section className="table-card"><div className="section-head"><div><p className="eyebrow">{nodes.length} 台服务器</p><h3>被控端服务器</h3></div><button className="outline" onClick={onAdd}>＋ 添加服务器</button></div><div className="node-cards">{nodes.map(n=><article key={n.id}><div className="node-card-top"><span className={`node-icon large ${n.status}`}>{n.role==="ingress"?"IN":"OUT"}</span><em className={n.status}>{n.status==="online"?"在线":"离线"}</em></div><h3>{n.name}</h3><p>{roleName(n.role)}服务器</p><dl><div><dt>公网地址</dt><dd>{n.public_address||"—"}</dd></div><div><dt>内网地址</dt><dd>{n.private_address}</dd></div><div><dt>网卡</dt><dd>{n.public_interface} / {n.private_interface}</dd></div></dl><button className="danger-link" onClick={()=>onDelete(n.id)}>删除服务器</button></article>)}</div>{!nodes.length&&<Empty title="尚未添加服务器" description="安装 Agent 后，服务器将在这里显示。" action={onAdd}/>}</section>}

function Rules({nodes,rules,onAdd,onToggle,onDelete}:{nodes:Node[];rules:Rule[];onAdd:()=>void;onToggle:(r:Rule)=>void;onDelete:(id:string)=>void}){return <section className="table-card"><div className="section-head"><div><p className="eyebrow">两种接管模式</p><h3>全部转发</h3></div><button className="outline" onClick={onAdd}>＋ 新建转发</button></div>{rules.length?<div className="data-table"><div className="table-row table-labels"><span>规则</span><span>链路</span><span>目标</span><span>限速</span><span>状态</span><span/></div>{rules.map(r=><div className="table-row" key={r.id}><span><i className={`protocol ${r.protocol}`}>{r.protocol.toUpperCase()}</i><b>{r.name}</b><small>{r.mode==="dual_managed"?"双端托管":"仅出口接管"} · {r.engine}</small></span><span><b>{r.mode==="dual_managed"?`${nodeName(nodes,r.ingress_node_id)} :${r.listen_port}`:`已有入口 → ${r.listen_address}:${r.listen_port}`}</b><small>→ {nodeName(nodes,r.egress_node_id)}{r.mode==="dual_managed"?` :${r.relay_port}`:""}</small></span><span><b>{r.target_host}</b><small>端口 {r.target_port}</small></span><span><b>↓ {r.download_mbps||"∞"} Mbps</b><small>↑ {r.upload_mbps||"∞"} Mbps</small></span><span><button className={`switch ${r.enabled?"on":""}`} onClick={()=>onToggle(r)}><i/></button><small>{r.enabled?"运行中":"已暂停"}</small></span><span><button className="icon-button danger" onClick={()=>onDelete(r.id)}>×</button></span></div>)}</div>:<Empty title="还没有转发规则" description="选择双端托管或仅出口接管，创建第一条转发。" action={onAdd}/>}</section>}

function Traffic({rules,points,summary}:{rules:Rule[];points:Point[];summary:Summary}){return <div className="traffic-page"><section className="stats-row"><Metric label="今日下载" value={bytes(summary.today_download)} note="规则接管侧统计" tone="violet"/><Metric label="今日上传" value={bytes(summary.today_upload)} note="每条链路只统计一次" tone="cyan"/><Metric label="今日合计" value={bytes(summary.today_upload+summary.today_download)} note="按分钟聚合" tone="green"/></section><section className="chart-card full"><div className="section-head"><div><p className="eyebrow">流量采样</p><h3>全规则趋势</h3></div><span className="tag">24 小时</span></div><TrafficChart points={points}/></section><section className="table-card"><div className="section-head"><div><p className="eyebrow">统计口径</p><h3>规则流量与策略</h3></div></div><div className="data-table traffic-table">{rules.map(r=><div className="table-row" key={r.id}><span><i className={`protocol ${r.protocol}`}>{r.protocol.toUpperCase()}</i><b>{r.name}</b></span><span><small>上传限制</small><b>{r.upload_mbps?`${r.upload_mbps} Mbps`:"不限速"}</b></span><span><small>下载限制</small><b>{r.download_mbps?`${r.download_mbps} Mbps`:"不限速"}</b></span><span><small>突发</small><b>{r.burst_kbytes} KB</b></span><span><small>统计</small><b className="good">已启用</b></span></div>)}</div></section></div>}

function Empty({title,description,action}:{title:string;description:string;action:()=>void}){return <div className="empty"><span>⇄</span><h3>{title}</h3><p>{description}</p><button className="primary" onClick={action}>开始配置</button></div>}

function RuleModal({nodes,busy,onClose,onSave}:{nodes:Node[];busy:boolean;onClose:()=>void;onSave:(r:Omit<Rule,"id">)=>void}){
  const firstIngress=nodes.find(n=>n.role!=="egress"),firstEgress=nodes.find(n=>n.id!==firstIngress?.id&&n.role!=="ingress")||nodes.find(n=>n.role!=="ingress");
  const [r,setR]=useState(()=>({...emptyRule,ingress_node_id:firstIngress?.id||"",egress_node_id:firstEgress?.id||""}));
  const field=(key:keyof typeof r)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setR({...r,[key]:e.target.type==="number"?Number(e.target.value):e.target.value});
  const ingress=nodes.find(n=>n.id===r.ingress_node_id),egress=nodes.find(n=>n.id===r.egress_node_id);
  const setMode=(mode:Rule["mode"])=>setR({...r,mode,listen_address:mode==="exit_only"?(egress?.private_address||""):"0.0.0.0",relay_port:0});
  const setEgress=(id:string)=>{const server=nodes.find(n=>n.id===id);setR({...r,egress_node_id:id,listen_address:r.mode==="exit_only"?(server?.private_address||""):r.listen_address})};
  const ready=r.mode==="dual_managed"?Boolean(ingress&&egress&&ingress.id!==egress.id):Boolean(egress&&r.listen_address);
  return <Modal title="新建转发" onClose={onClose}>
    <form className="form-grid simple-rule" onSubmit={e=>{e.preventDefault();onSave({...r,target_port:r.target_port||r.listen_port,ingress_node_id:r.mode==="exit_only"?r.egress_node_id:r.ingress_node_id,relay_port:r.mode==="exit_only"?r.listen_port:0})}}>
      <div className="mode-picker full"><button type="button" className={r.mode==="dual_managed"?"selected":""} onClick={()=>setMode("dual_managed")}><b>双端托管</b><span>广州和香港都安装 Agent</span><small>广州公网 → 香港内网 → 落地</small></button><button type="button" className={r.mode==="exit_only"?"selected":""} onClick={()=>setMode("exit_only")}><b>仅出口接管</b><span>广州到香港已配置好</span><small>香港内网接入 → 落地</small></button></div>
      {r.mode==="dual_managed"?<>
        <label>广州入口服务器<select required value={r.ingress_node_id} onChange={field("ingress_node_id")}><option value="">请选择</option>{nodes.filter(n=>n.role!=="egress").map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label>
        <label>香港出口服务器<select required value={r.egress_node_id} onChange={e=>setEgress(e.target.value)}><option value="">请选择</option>{nodes.filter(n=>n.role!=="ingress"&&n.id!==r.ingress_node_id).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label>
        <div className="auto-route full"><span>主控自动部署两段</span><b>{ingress?.name||"广州入口"} → {egress?.private_address||"香港内网 IP"} → 落地</b><small>中继端口自动分配；香港从公网 IP 发往落地</small></div>
      </>:<>
        <label className="full">香港出口服务器<select required value={r.egress_node_id} onChange={e=>setEgress(e.target.value)}><option value="">请选择</option>{nodes.filter(n=>n.role!=="ingress").map(n=><option key={n.id} value={n.id}>{n.name} · {n.private_address}</option>)}</select></label>
        <label className="full">香港内网接入 IP<input required value={r.listen_address} onChange={field("listen_address")} placeholder="广州现有规则转入的香港内网 IP"/><small>通常自动使用该出口服务器的内网 IP</small></label>
        <div className="auto-route full"><span>主控只部署出口段</span><b>已有广州转发 → {r.listen_address||"香港内网 IP"}:{r.listen_port} → 落地</b><small>广州入口无需安装 Agent，第一段由你已有的规则负责</small></div>
      </>}
      <label>转发引擎<select value={r.engine} onChange={field("engine")}><option value="nftables">nftables（内核转发）</option><option value="realm">Realm</option></select></label>
      <label>{r.mode==="dual_managed"?"广州公网端口":"香港内网接入端口"}<input required type="number" min="1" max="65535" value={r.listen_port} onChange={field("listen_port")}/></label>
      <label className="full">落地 IP<input required value={r.target_host} onChange={field("target_host")} placeholder="例如：192.0.2.88"/></label>
      <label className="full">落地端口（可选）<input type="number" min="0" max="65535" value={r.target_port||""} onChange={field("target_port")} placeholder={`默认与接入端口相同：${r.listen_port}`}/></label>
      <details className="advanced full"><summary>高级设置：速率控制</summary><div className="advanced-grid"><label>上传限速（Mbps）<input type="number" min="0" value={r.upload_mbps} onChange={field("upload_mbps")}/><small>0 表示不限速</small></label><label>下载限速（Mbps）<input type="number" min="0" value={r.download_mbps} onChange={field("download_mbps")}/><small>0 表示不限速</small></label><label>突发流量（KB）<input type="number" min="32" value={r.burst_kbytes} onChange={field("burst_kbytes")}/></label></div></details>
      <div className="modal-actions full"><button type="button" className="outline" onClick={onClose}>取消</button><button className="primary" disabled={busy||!ready}>{busy?"下发中…":r.mode==="dual_managed"?"创建并下发两端":"创建并下发出口"}</button></div>
    </form>
  </Modal>
}

function NodeModal({busy,credential,onClose,onSave}:{busy:boolean;credential:{nodeId:string;token:string}|null;onClose:()=>void;onSave:(n:typeof emptyNode)=>void}){const [n,setN]=useState(emptyNode);const field=(key:keyof typeof n)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setN({...n,[key]:e.target.value} as typeof n);return <Modal title={credential?"服务器已创建":"添加被控服务器"} onClose={onClose}>{credential?<div className="token-box"><span>Server ID</span><code>{credential.nodeId}</code><span>Agent Token（仅显示一次）</span><code>{credential.token}</code><p>把两项内容复制到该服务器的 Agent 配置中并妥善保存。</p><button className="primary wide" onClick={()=>navigator.clipboard.writeText(`node_id=${credential.nodeId}\ntoken=${credential.token}`)}>复制凭据</button></div>:<form className="form-grid" onSubmit={e=>{e.preventDefault();onSave(n)}}><label className="full">服务器名称<input required value={n.name} onChange={field("name")} placeholder="例如：香港出口"/></label><label>服务器用途<select value={n.role} onChange={field("role")}><option value="ingress">入口服务器</option><option value="egress">出口服务器</option><option value="both">入口 / 出口均可</option></select></label><label>公网地址<input value={n.public_address} onChange={field("public_address")} placeholder="出口访问落地使用"/></label><label>内网地址<input required value={n.private_address} onChange={field("private_address")} placeholder="例如：10.24.0.3"/></label><label>公网网卡<input required value={n.public_interface} onChange={field("public_interface")}/></label><label>内网网卡<input required value={n.private_interface} onChange={field("private_interface")}/></label><div className="modal-actions full"><button type="button" className="outline" onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?"创建中…":"创建服务器"}</button></div></form>}</Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><section className="modal"><div className="modal-head"><div><p className="eyebrow">配置</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}>×</button></div>{children}</section></div>}
